name: Trigger auto deployment for webapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/webapi-AutoDeployTrigger-c911e98e-a63c-421a-8237-d2f570bf3376.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.WEBAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: cae5ab398244acr.azurecr.io
          registryUsername: ${{ secrets.WEBAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.WEBAPI_REGISTRY_PASSWORD }}
          containerAppName: webapi
          resourceGroup: rg-aca-from-github-action
          imageToBuild: cae5ab398244acr.azurecr.io/webapi:${{ github.sha }}
          
            

     

